// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/leokuzmanovic/go-echo-example/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// BooksService is an autogenerated mock type for the BooksService type
type BooksService struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: ctx, title, author
func (_m *BooksService) CreateBook(ctx context.Context, title string, author string) (*models.Book, error) {
	ret := _m.Called(ctx, title, author)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 *models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Book, error)); ok {
		return rf(ctx, title, author)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Book); ok {
		r0 = rf(ctx, title, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, title, author)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookById provides a mock function with given fields: ctx, id
func (_m *BooksService) DeleteBookById(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookById provides a mock function with given fields: ctx, id
func (_m *BooksService) GetBookById(ctx context.Context, id string) (*models.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookById")
	}

	var r0 *models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Book); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBooksService creates a new instance of BooksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBooksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BooksService {
	mock := &BooksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
